WebApplication1/Models/Oyun.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication1.Models 
{
    public class Oyun
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public double Fiyat { get; set; }
        public string Kategori { get; set; }
        public DateTime Tarih { get; set; }
        public int Puan { get; set; }
        public string Video { get; set; }
        public string MinSistem { get; set; }
        public string OnerilenSistem { get; set; }
        public string Tanitim { get; set; }
        public string Platform { get; set; }
        public int StokDurumu { get; set; }
        public string scr1 { get; set; }
        public string scr2 { get; set; }
        public string scr3 { get; set; }
        public string scr4 { get; set; }
        public string scr5 { get; set; }
        public string scr6 { get; set; }
        public string cover { get; set; }
        public string banner { get; set; }
        public int Satilan { get; set; }

        public virtual ICollection<Yorum> Yorumlar { get; set; }
        public virtual ICollection<CdKey> CdKey { get; set; }
    }
}

WebApplication1/Controllers/OdemeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Veri;
using WebApplication1.Models;
using System.Data.Entity.Validation;
using System.Data;
using System.Data.Entity;

namespace WebApplication1.Controllers
{
    public class OdemeController : Controller
    {
        //
        // GET: /Odeme/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Oyun(int oyunId)
        {
            SarayContext db = new SarayContext();
            Oyun Oyun = db.Oyunlar.Where(x => x.Id == oyunId).SingleOrDefault();
            ViewData["id"] = oyunId.ToString();
            return View(Oyun);
        }
        [HttpPost]
        public ActionResult Oyun(string oyunId,string kullaniciId)
        {
            int oid = Convert.ToInt32(oyunId);
            int kid = Convert.ToInt32(kullaniciId);
            using (SarayContext db=new SarayContext())
            {
                Oyun Oyun = db.Oyunlar.Where(x => x.Id == oid).SingleOrDefault();
                Kullanici Kullanici = db.Kullanicilar.Where(i => i.ID == kid).SingleOrDefault();
                var _oyun = db.Oyunlar.Single(a => a.Id == oid);
                var _kullanici = db.Kullanicilar.Single(a => a.ID == kid);
                Oyun.StokDurumu = db.CdKey.Where(x => x.Durum == false).Count()-1;
                if (_kullanici.Bakiye>=_oyun.Fiyat)
                {
                Kullanici.Bakiye = Convert.ToDouble( Kullanici.Bakiye) -Convert.ToDouble(Oyun.Fiyat);
                Oyun.StokDurumu = Convert.ToInt32(Oyun.StokDurumu) - 1;
                db.Entry(_oyun).CurrentValues.SetValues(Oyun);
                db.Entry(_kullanici).CurrentValues.SetValues(Kullanici);
                db.SaveChanges();
                CdKey _cdkey = _oyun.CdKey.Where(x => x.Durum == false).First();
                Kullanici.OyunSiparis.Add(new OyunSiparis { 
                    CdKey=_cdkey,
                    Oyun=_oyun,
                    OyunID=_oyun.Id,
                    CdKeyID=_cdkey.CdKeyID,
                    Tarih=DateTime.Now
                });
                CdKey cdkey = _cdkey;
                cdkey.Durum = true;//true satılmış demek.
                db.Entry(_cdkey).CurrentValues.SetValues(cdkey);
                db.SaveChanges();

                Session["Bakiye"] = _kullanici.Bakiye.ToString();
                }
                else
                {
                    return RedirectToAction("Basarisiz");
                }
          
            return RedirectToAction("Basarili");
            }
        }
        public ActionResult Basarili()
        {
            return View();
        }
        public ActionResult Basarisiz()
        {
            return View();
        }
        public ActionResult ParaYukle()
        {
            return View();
        }
	}
}

WebApplication1/Controllers/OyunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Veri;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class OyunController : Controller
    {
        SarayContext db = new SarayContext();
        //
        // GET: /Oyun/
        public ActionResult Index()
        {
            SarayContext db = new SarayContext();
            List<Oyun> Oyunlar = db.Oyunlar.OrderByDescending(x => x.Tarih).ToList();
            return View(Oyunlar);
        }
        public ActionResult Oyunlar(string kategori)
        {
            ViewData["kategori"] = kategori;
            using (SarayContext db = new SarayContext())
            {

                List<Oyun> Oyunlar = db.Oyunlar.Where(x => x.Kategori.Contains(kategori)).ToList();
                return View(Oyunlar);
            }
        }
        public ActionResult id(int id)
        {
            List<object> myModel = new List<object>();
            myModel.Add(db.Oyunlar.OrderBy(x => x.Tarih).ToList());
            myModel.Add(db.Kullanicilar.ToList());
            myModel.Add(db.Yorumlar.OrderBy(x=>x.Tarih).ToList());
            ViewData["id"] = id.ToString();
            return View(myModel);
        }

        public ActionResult Oyun(int id)
        {
            SarayContext db = new SarayContext();
            Oyun Oyun = db.Oyunlar.Where(x => x.Id == id).SingleOrDefault();
            ViewData["id"] = id.ToString();
            return View(Oyun);
        }
        [HttpPost]
        public ActionResult Oyun(int id, int KullaniciID, string YorumTuru, string Icerik)
        {
            using (SarayContext db = new SarayContext())
            { 
                Yorum _yrm = new Yorum();
                _yrm.OyunID = id;
                _yrm.KullaniciID = KullaniciID;
                _yrm.YorumTuru = YorumTuru;
                _yrm.Icerik = Icerik;
                _yrm.Tarih = DateTime.Now;
                db.Yorumlar.Add(_yrm);
                db.SaveChanges();
            }
            ModelState.Clear();
                SarayContext dba = new SarayContext();
                Oyun Oyun = dba.Oyunlar.Where(x => x.Id == id).SingleOrDefault();
                ViewData["id"] = id.ToString();
                return View(Oyun);

        }
        [HttpPost]
        public ActionResult id(int OyunID, int KullaniciID, string YorumTuru, string Icerik)
        {
            using (SarayContext db = new SarayContext())
            {
                Yorum _yrm = new Yorum();
                _yrm.OyunID = OyunID;
                _yrm.KullaniciID = KullaniciID;
                _yrm.YorumTuru = YorumTuru;
                _yrm.Icerik = Icerik;
                _yrm.Tarih = DateTime.Now;
                db.Yorumlar.Add(_yrm);
                db.SaveChanges();
                List<object> myModel = new List<object>();
                myModel.Add(db.Oyunlar.ToList());
                myModel.Add(db.Kullanicilar.ToList());
                myModel.Add(db.Yorumlar.ToList());
                ViewData["id"] = OyunID.ToString();
                return View(myModel);
            }
        }
        public ActionResult TabYeniCikanlar()
        {
            int i = 0;
            SarayContext db = new SarayContext();
            List<Oyun> _Oyun = new List<Oyun>();
            List<Oyun> Oyun = new List<Oyun>();
            _Oyun=(db.Oyunlar.OrderByDescending(x => x.Tarih).ToList());
            foreach (var item in _Oyun)
            {
                Oyun.Add(item);
                i++;
                if (i>=4)
                {
                    break;
                }
            }
            return View(Oyun);
        }

        public ActionResult TabCokSatanlar()
        {
            int i = 0;
            SarayContext db = new SarayContext();
            List<Oyun> _Oyun = new List<Oyun>();
            List<Oyun> Oyun = new List<Oyun>();
            _Oyun = (db.Oyunlar.OrderByDescending(x => x.Satilan).ToList());
            foreach (var item in _Oyun)
            {
                Oyun.Add(item);
                i++;
                if (i >= 4)
                {
                    break;
                }
            }
            return View(Oyun);
        }


        public ActionResult TabBenzerler(Oyun oyn)
        {
            int adUz, katUz;
            SarayContext db = new SarayContext();
            List<Oyun> Oyun = new List<Oyun>();
            List<Oyun> ad=new List<Oyun>();
            List<Oyun> kategori = new List<Oyun>();
            List<Oyun> genel = new List<Oyun>();
            int i = 0;
            char[] delimiterChars = { ' ', ',', '.', ':', '\t' };
            string[] oyunAdiKelime = oyn.Adi.Split(delimiterChars);
            string[] kategoriKelime = oyn.Kategori.Split(delimiterChars);
            foreach (string s in oyunAdiKelime)
            {
                ad= db.Oyunlar.Where(x => x.Adi.Contains(s)).ToList();
                ad.Remove(db.Oyunlar.Where(x => x.Id == oyn.Id).Single());
            }
            adUz = ad.Count();
            foreach (string s in kategoriKelime)
            {
                kategori = db.Oyunlar.Where(x => x.Adi.Contains(s)).ToList();
                kategori.Remove(db.Oyunlar.Where(x => x.Id == oyn.Id).Single());
            }
            katUz = kategori.Count();
            genel = db.Oyunlar.ToList();
            genel.Remove(db.Oyunlar.Where(x => x.Id == oyn.Id).Single());
            foreach (var item in ad)
            {
                Oyun.Add(item);
                i++;
                if (i >= 4)
                {
                    break;
                }
            }
            i = 0;
            if (adUz<4)
            {
                foreach (var item in kategori)
                {
                    Oyun.Add(item);
                    i++;
                    if (i >= (4-adUz))
                    {
                        break;
                    }
                }
                i = 0;
                if (adUz+katUz<4)
                {
                    foreach (var item in genel)
                    {
                        Oyun.Add(item);
                        i++;
                        if (i >= (4 - adUz+katUz))
                        {
                            break;
                        }
                    }
                }
            }
            return View(Oyun);
        }

    }
}

WebApplication1/Views/Oyun/Index.cshtml
@model IEnumerable<WebApplication1.Models.Oyun>
@{  
    ViewBag.Title = "Oyunlar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container" style="background-color: rgba(0, 0, 0, 0.94); min-width:100%; padding:3%;" align="center">
    SLİDER
</div>
<br />
<div class="container" style="min-width:100%; padding:0px; padding-bottom:3%;">
    <div class="col-md-9" style="margin:0px; padding:0px; padding-right:1%; padding-bottom:2%;">
        <div class="container" style="background-color: rgba(0, 0, 0, 0.94); padding-top:5%; padding-bottom:5%;" align="center">
                @foreach (var item in Model)
                {
                    <a href="@Url.Action("Oyun", "Oyun", new { id=item.Id})">
                        <div class=" col-xs-6 col-md-3" style="border: 1px solid #232323; margin: 0px; padding-top:3%; padding-bottom: 3%;">
                            <img id="cover" src="@(item.cover)" />
                            <div class="row" id="info">
                                @item.Adi
                                <br />
                                <span class="text-primary">@(item.Fiyat) ₺</span>
                            </div>
                        </div>
                    </a>
                }
        </div>
        <br />
        <button class="btn btn-default" style="background-color: rgba(0, 0, 0, 1); color: white; width:100%; border:1px solid #000000">DAHA FAZLA GÖSTER</button>


    </div>
    <div class="col-md-3" style="margin:0px; padding:0px;">
        <div class="container" style="background-color:rgba(0,0,0,94); padding:2%;">
            <div class="row" id="GradTransparanSiyahTransparan" style="color:azure;" align="center">
                <h4>KATEGORİLER</h4>
            </div>
            <a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Aksiyon"})"><input type="button" id="ktgr" value="Aksiyon" style="min-width:100%;" /><br /></a>
            <a href="@Url.Action("Oyunlar", "Oyun", new { kategori="FPS"})"><input type="button" id="ktgr" value="FPS" style="min-width:100%;" /><br /></a>
            <a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Eglence"})"><input type="button" id="ktgr" value="Eğlence" style="min-width:100%;" /><br /></a>
            <a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Macera"})"><input type="button" id="ktgr" value="Macera" style="min-width:100%;" /><br /></a>
            <a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Simulasyon"})"><input type="button" id="ktgr" value="Simülasyon" style="min-width:100%;" /><br /></a>
            <div class="row" id="GradTransparanSiyahTransparan" style="color:azure;" align="center">
            </div>
        </div>
    </div>
</div>

WebApplication1/Views/Oyun/Oyun.cshtml
@model WebApplication1.Models.Oyun

@{
    ViewBag.Title = Model.Adi;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="jumbotron" style="background-color: rgba(0, 0, 0, 0.94); padding-top:0px; padding-bottom:0px; ">
    <div class=" row" style="">
        <h4 style="float:left;">@Model.Adi</h4>
        <h5 style="float:right; color:rgba(87, 250, 71, 0.89);">@Model.Puan</h5>
        <h5 style="float:right; color:rgb(179, 179, 179);">Site Puanı :</h5>

    </div>
</div>


<div class="jumbotron" style="background-color: rgba(0, 0, 0, 0.94);  " align="center">
    <div class="row" id="GradTransparanSiyahTransparan" style="">
        @(Model.Adi)
    </div>
    <div class="row" style="padding-bottom: 3%; padding-top: 2%; border-top: 1px solid #232323;">
        <div class="col-xs-4 col-sm-4 col-md-2" style="">
            <img src="@(Model.cover)" style="width: 100%; border: 5px solid #232323;" />
        </div>

        <div class="col-xs-8 col-sm-8 col-md-10">
            <div class="col-xs-12">
                <div class="row" style="color: rgba(143, 143, 143, 0.80)" align="left">
                    <p style="font-size:13px;">
                        @Model.Tanitim
                    </p>
                </div>
                <div class="row" style=" color:rgba(141, 255, 240, 0.74);font-size:14px; ">
                    <p style="color: rgba(187, 74, 74, 0.95); float: left;">Kategori:</p>
                    <p style="float:left">@(Model.Kategori) </p>
                    <p style="color: rgba(187, 74, 74, 0.95); float: right; ">
                        Platform:<img src="/img/icon/@(Model.Platform).png" style="width:20px; height:20px;" />
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style=" border-top: 1px solid #232323;">
        <div class=" col-md-5" style="">
            <div class="row" style="">
                <div class="col-xs-12">

                    <div class='embed-container'><iframe src='@Model.Video' frameborder='0'></iframe></div>

                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="row">
                <div class="col-xs-4" style="padding-bottom: 10px;">
                    <div class="Scr" id="myImg" data-toggle="modal" data-target="#myModal" style="border:1px solid #232323; width:100%; padding-top:56.25%; background-image:url('@(Model.scr1)'); background-size:cover;"></div>
                </div>
                <div class="col-xs-4" style="padding-bottom: 10px;">
                    <div class="Scr" id="myImg" data-toggle="modal" data-target="#myModal" style="border:1px solid #232323; width:100%; padding-top:56.25%; background-image:url('@(Model.scr2)'); background-size:cover;"></div>
                </div>
                <div class="col-xs-4" style="padding-bottom: 10px;">
                    <div class="Scr" id="myImg" data-toggle="modal" data-target="#myModal" style="border:1px solid #232323; width:100%; padding-top:56.25%; background-image:url('@(Model.scr3)'); background-size:cover;"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4" style="padding-bottom: 10px;">
                    <div class="Scr" id="myImg" data-toggle="modal" data-target="#myModal" style="border:1px solid #232323; width:100%; padding-top:56.25%; background-image:url('@(Model.scr4)'); background-size:cover;"></div>
                </div>
                <div class="col-xs-4" style="padding-bottom: 10px;">
                    <div class="Scr" id="myImg" data-toggle="modal" data-target="#myModal" style="border:1px solid #232323; width:100%; padding-top:56.25%; background-image:url('@(Model.scr5)'); background-size:cover;"></div>
                </div>
                <div class="col-xs-4" style="padding-bottom: 10px;">
                    <div class="Scr" id="myImg" data-toggle="modal" data-target="#myModal" style="border:1px solid #232323; width:100%; padding-top:56.25%; background-image:url('@(Model.scr6)'); background-size:cover;"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style=" border-top: 1px solid #232323;">
        <div class="col-md-6">
            <h5 style="color:rgba(248, 123, 116, 0.92)">Minimum Sitem Gereksinimleri</h5>
            <hr />
            <div class="row" style="color:rgba(143, 143, 143, 0.80)" align="center">
                <p style="font-size:13px;">
                    @Model.MinSistem
                </p>
            </div>
        </div>
        <div class="col-md-6">
            <h5 style="color:rgba(120, 197, 255, 0.89)">Önerilen Sitem Gereksinimleri</h5>
            <hr />
            <div class="row" style="color: rgba(143, 143, 143, 0.80)" align="center">
                <p style="font-size:13px;">
                    @Model.OnerilenSistem
                </p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12" style="border:solid 1px #808080; background-color:rgba(47, 47, 47, 0.38)">
            @(Model.Adi) CD-KEY SATIN ALIN @(Model.Fiyat) ₺
            <a class="btn btn-danger btn-md" href="@Url.Action("Oyun", "Odeme", new { oyunId=Model.Id})">Sepete Ekle</a>
        </div>
    </div>
</div>



<div class="jumbotron" style="background-color: rgba(0, 0, 0, 0.94); padding-top:0px; ">
    <div class="row" id="GradTransparanSiyahTransparan" style="" align="center">
        YORUMLAR
    </div>
    @foreach (var item in Model.Yorumlar)
    {
        <div class="row" style="padding-bottom: 3%; padding-top: 2%; border-top: 1px solid #232323; border-bottom: 1px solid #232323;">
            <div class="col-xs-3 col-sm-2 col-md-1" style="font-size:13px; " align="center">
                @item.Kullanici.KullaniciAdi
                <br />
                <img class=" img-rounded" id="profilResmi" src="/img/profil/@(item.Kullanici.ProfilResmi)" />
            </div>
            <div class="col-xs-9 col-sm-10 col-md-11" id="yorum">
                <p style="">
                    @item.Icerik
                </p>
            </div>
        </div>
    }
    @if (Session["KullaniciID"] != null)
    {
        <div class="row" style="">
            @using (Html.BeginForm("Oyun", "Oyun", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                  @Html.AntiForgeryToken()
                <div class="form-group">
                    <label style="font-size:14px; color:rgba(123, 123, 123, 0.81)" for="comment">Görüşünüzü Paylaşın :</label>
                    @Html.Hidden("OyunID", Model.Id)
                    @Html.Hidden("KullaniciID", Session["KullaniciID"])
                    @Html.Hidden("YorumTuru", "Oyun")
                    @Html.TextArea("Icerik", null, new { @class = "form-control", placeholder = "Mesajınız", rows = 6, columns = 40 })
                </div>
                <button type="submit" class="btn btn-default" style="color:white; background-color:rgba(117, 117, 117, 0.93)" name="yorum_buton">Yorum Ekle</button>
            }

        </div>
    }
</div>




<div class="jumbotron" style="background-color: rgba(0, 0, 0, 0.94); " align="center">
    <div class="row" style="border:1px solid #232323; padding-bottom:4%;">
        <div class="col-md-7">
            <ul class="nav nav-tabs" style="border-bottom: 1px solid #232323;">
                <!--<li class="active"><a data-toggle="tab" href="#home">Home</a></li>-->
                <li class="active"><a style="color: white; background-color: rgba(0, 0, 0, 0.90); font-size: 15px;" data-toggle="tab" href="#menu1">Yeni Çıkanlar</a></li>
                <li><a style="color: white; background-color: rgba(0, 0, 0, 0.90); font-size: 15px; " data-toggle="tab" href="#menu2">Çok Satanlar</a></li>
            </ul>
            <div class="tab-content" style="width: 100%; font-size: 13px; color: rgb(208, 208, 208); border-right: 1px solid #232323;">
                <!--<div id="home" class="tab-pane fade in active">
                    <h3>HOME</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                </div>-->
               
                <div id="menu1" class="tab-pane active">
                    @Html.Action("TabYeniCikanlar", "Oyun")
                </div>
                <div id="menu2" class="tab-pane fade">
                    @Html.Action("TabCokSatanlar", "Oyun")
                </div>
            </div>
        </div>
        <div class="col-md-5" style="">
            <div class="row" id="GradTransparanSiyahTransparan" style="color:azure;" align="center">
                <h4>BENZER ÜRÜNLER</h4>
            </div>

            <div class="row">
                @Html.Action("TabBenzerler", "Oyun", new { oyn = Model })
            </div>
        </div>
    </div>
</div>




<div id="myModal" class="modal fade" role="dialog">

    <span class="close" data-dismiss="modal">&times;</span>
    <div class="modal-content">
        <div class="modal-body">
            <img class="img-responsive" src="" />
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('.Scr').on('click', function () {
            var bg = $(this).css('background-image');
            var image = bg.replace(/^url\(/, "");
            image = image.replace(/\)/, "");
            image = image.replace(/\"/, "");
            image = image.replace(/\"/, "");
            $('#myModal').on('show.bs.modal', function () {
                $(".img-responsive").attr("src", image);
            });
        });
    });
</script>

WebApplication1/Views/Oyun/Oyunlar.cshtml
@model IEnumerable<WebApplication1.Models.Oyun>
@{
    ViewBag.Title = "Oyunlar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container" style="background-color: rgba(0, 0, 0, 0.94); min-width:100%; padding:3%;" align="center">
    SLİDER
</div>
 <br />
<div class="container" style="background-color: rgba(0, 0, 0, 0.94); min-width:100%;" align="center">
    @ViewData["Kategori"] Oyunları
</div>
    <br />
    <div class="container" style="min-width:100%; padding:0px; padding-bottom:3%;">
        <div class="col-md-9" style="margin:0px; padding:0px; padding-right:1%; padding-bottom:2%;">
            <div class="container" style="background-color: rgba(0, 0, 0, 0.94); padding-top:5%; padding-bottom:5%;" align="center">
                @foreach (var item in Model)
                {
                    <a href="@Url.Action("Oyun", "Oyun", new { id=item.Id})">
                        <div class=" col-xs-6 col-md-3" style="border: 1px solid #232323; margin: 0px; padding-top:3%; padding-bottom: 3%;">
                            <img id="cover" src="@(item.cover)" />
                            <div class="row" id="info">
                                @item.Adi
                                <br />
                                <span class="text-primary">@(item.Fiyat) ₺</span>
                            </div>
                        </div>
                    </a>
                }
            </div>
            <br />
            <button class="btn btn-default" style="background-color: rgba(0, 0, 0, 1); color: white; width:100%; border:1px solid #000000">DAHA FAZLA GÖSTER</button>


        </div>
        <div class="col-md-3" style="margin:0px; padding:0px;">
            <div class="container" style="background-color:rgba(0,0,0,94); padding:2%;">
                <div class="row" id="GradTransparanSiyahTransparan" style="color:azure;" align="center">
                    <h4>KATEGORİLER</h4>
                </div>
                <a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Aksiyon"})"><input type="button" id="ktgr" value="Aksiyon" style="min-width:100%;" /><br /></a>
                <a href="@Url.Action("Oyunlar", "Oyun", new { kategori="FPS"})"><input type="button" id="ktgr" value="FPS" style="min-width:100%;" /><br /></a>
                <a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Eglence"})"><input type="button" id="ktgr" value="Eğlence" style="min-width:100%;" /><br /></a>
                <a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Macera"})"><input type="button" id="ktgr" value="Macera" style="min-width:100%;" /><br /></a>
                <a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Simulasyon"})"><input type="button" id="ktgr" value="Simülasyon" style="min-width:100%;" /><br /></a>
                <div class="row" id="GradTransparanSiyahTransparan" style="color:azure;" align="center">
                </div>
            </div>
        </div>
    </div>

WebApplication1/Views/Oyun/TabBenzerler.cshtml
@model IEnumerable<WebApplication1.Models.Oyun>

@{
    Layout = null;
}

@foreach (var item in Model)
{
    <a href="@Url.Action("Oyun", "Oyun", new { id=item.Id})">
        <div class=" col-xs-6 col-md-6" style="border: 1px solid #232323; margin: 0px; padding-top:3%; padding-bottom: 3%;">
            <img id="cover" src="@(item.cover)" />
            <div class="row" id="info">
                @item.Adi
                <br />
                <span class="text-primary">@(item.Fiyat) ₺</span>
            </div>
        </div>
    </a>
}

WebApplication1/Views/Oyun/TabCokSatanlar.cshtml
@model IEnumerable<WebApplication1.Models.Oyun>

@{
    Layout = null;
}

@foreach (var item in Model)
{
    <a href="@Url.Action("Oyun", "Oyun", new { id=item.Id})">
        <div class="row" id="banner" style="padding-top: 2%;">
            <div class="col-xs-12">
                <div class="col-xs-5" style="padding-left:0px;">
                    <img src="@(item.banner)" style="width:100%;" />
                </div>
                <div class="col-xs-7" id="GradTransparanSiyahTransparan" style=" " align="center">
                    <h5 style="color:white">@(item.Adi)</h5>
                    <h5>@(item.Fiyat) ₺</h5>
                </div>
            </div>
        </div>
    </a>
}

WebApplication1/Views/Oyun/TabYeniCikanlar.cshtml
@model IEnumerable<WebApplication1.Models.Oyun>

@{
    Layout = null;
}

@foreach (var item in Model)
{
    <a href="@Url.Action("Oyun", "Oyun", new { id=item.Id})">
        <div class="row" id="banner" style="padding-top: 2%;">
            <div class="col-xs-12">
                <div class="col-xs-5" style="padding-left:0px;">
                    <img src="@(item.banner)" style="width:100%;" />
                </div>
                <div class="col-xs-7" id="GradTransparanSiyahTransparan" style=" " align="center">
                    <h5 style="color:white">@(item.Adi)</h5>
                    <h5>@(item.Fiyat) ₺</h5>
                </div>
            </div>
        </div>
    </a>
}

WebApplication1/Views/Oyun/Tabs.cshtml
@model IEnumerable<WebApplication1.Models.Oyun>

@{
    Layout = null;
}