WebApplication1/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Veri;
    
namespace WebApplication1.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult OyunEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult OyunEkle(Oyun oyn)
        {
            using (SarayContext db = new SarayContext())
            {
                oyn.Tarih = DateTime.Now;
                oyn.StokDurumu = 0;
                oyn.Satilan = 0;
                oyn.cover = "/img/cover/infc.jpg";
                oyn.scr1 = "/img/scr/infs.jpg";
                oyn.scr2 = "/img/scr/infs.jpg";
                oyn.scr3 = "/img/scr/infs.jpg";
                oyn.scr4 = "/img/scr/infs.jpg";
                oyn.scr5 = "/img/scr/infs.jpg";
                oyn.scr6 = "/img/scr/infs.jpg";
                oyn.banner = "/img/banner/infb.jpg";
                db.Oyunlar.Add(oyn);
                db.SaveChanges();

                return RedirectToAction("OyunResimEkle", new {oyunId=db.Oyunlar.OrderByDescending(x=>x.Tarih).First().Id.ToString() });
            }
        }
        public ActionResult OyunResimEkle(string oyunId)
        {
            int oid = Convert.ToInt32(oyunId);
            using   (SarayContext db = new SarayContext())
            { 
            Oyun Oyun = db.Oyunlar.Where(x => x.Id == oid).Single();
            
            return View(Oyun);
            }
        }
        [HttpPost]
        public ActionResult OyunResimEkle(string oyunId,string property,HttpPostedFileBase uploadfile)
        {
            string Klasor, filePath, pathForDb;
            int oid = Convert.ToInt32(oyunId);
            SarayContext db = new SarayContext();
            Oyun Oyun = db.Oyunlar.Where(x => x.Id == oid).Single();
            var _oyun = db.Oyunlar.Single(a => a.Id == oid);
            if (uploadfile.ContentLength > 0)
            {
                switch (property)
                {
                    case "cover":
                        Klasor = Path.Combine(Server.MapPath("~/img/cover"));
                        if (!Directory.Exists(Klasor))
                        {
                            DirectoryInfo di = Directory.CreateDirectory(Klasor);
                        }
                        filePath = Path.Combine(Klasor, (Oyun.Adi + Path.GetExtension(uploadfile.FileName)));
                        uploadfile.SaveAs(filePath);
                        pathForDb ="/img/cover/"+Oyun.Adi+Path.GetExtension(uploadfile.FileName);
                        Oyun.cover = pathForDb; 
                        break;
                    case "banner":
                        Klasor = Path.Combine(Server.MapPath("~/img/banner"));
                        if (!Directory.Exists(Klasor))
                        {
                            DirectoryInfo di = Directory.CreateDirectory(Klasor);
                        }
                        filePath = Path.Combine(Klasor, (Oyun.Adi + Path.GetExtension(uploadfile.FileName)));
                        uploadfile.SaveAs(filePath);
                        pathForDb = "/img/banner/" + Oyun.Adi + Path.GetExtension(uploadfile.FileName);
                        Oyun.banner = pathForDb;
                        break;
                    case "scrs1":
                        Klasor = Path.Combine(Server.MapPath("~/img/scr"), Oyun.Adi);
                        if (!Directory.Exists(Klasor))
                        {
                            DirectoryInfo di = Directory.CreateDirectory(Klasor);
                        }
                        filePath = Path.Combine(Klasor, ("scrs1" + Path.GetExtension(uploadfile.FileName)));
                        uploadfile.SaveAs(filePath);
                        pathForDb = "/img/scr/" + Oyun.Adi + "/" + "scrs1" + Path.GetExtension(uploadfile.FileName);
                        Oyun.scr1 = pathForDb;
                        break;
                    case "scrs2":
                        Klasor = Path.Combine(Server.MapPath("~/img/scr"), Oyun.Adi);
                        if (!Directory.Exists(Klasor))
                        {
                            DirectoryInfo di = Directory.CreateDirectory(Klasor);
                        }
                        filePath = Path.Combine(Klasor, ("scrs2" + Path.GetExtension(uploadfile.FileName)));
                        uploadfile.SaveAs(filePath);
                        pathForDb = "/img/scr/" + Oyun.Adi+"/" +"scrs2"+ Path.GetExtension(uploadfile.FileName);
                        Oyun.scr2 = pathForDb;
                        break;
                    case "scrs3":
                        Klasor = Path.Combine(Server.MapPath("~/img/scr"), Oyun.Adi);
                        if (!Directory.Exists(Klasor))
                        {
                            DirectoryInfo di = Directory.CreateDirectory(Klasor);
                        }
                        filePath = Path.Combine(Klasor, ("scrs3" + Path.GetExtension(uploadfile.FileName)));
                        uploadfile.SaveAs(filePath);
                        pathForDb = "/img/scr/" + Oyun.Adi + "/" + "scrs3" + Path.GetExtension(uploadfile.FileName);
                        Oyun.scr3 = pathForDb;
                        break;
                    case "scrs4":
                        Klasor = Path.Combine(Server.MapPath("~/img/scr"), Oyun.Adi);
                        if (!Directory.Exists(Klasor))
                        {
                            DirectoryInfo di = Directory.CreateDirectory(Klasor);
                        }
                        filePath = Path.Combine(Klasor, ("scrs4" + Path.GetExtension(uploadfile.FileName)));
                        uploadfile.SaveAs(filePath);
                        pathForDb = "/img/scr/" + Oyun.Adi + "/" + "scrs4" + Path.GetExtension(uploadfile.FileName);
                        Oyun.scr4 = pathForDb;
                        break;
                    case "scrs5":
                        Klasor = Path.Combine(Server.MapPath("~/img/scr"), Oyun.Adi);
                        if (!Directory.Exists(Klasor))
                        {
                            DirectoryInfo di = Directory.CreateDirectory(Klasor);
                        }
                        filePath = Path.Combine(Klasor, ("scrs5" + Path.GetExtension(uploadfile.FileName)));
                        uploadfile.SaveAs(filePath);
                        pathForDb = "/img/scr/" + Oyun.Adi + "/" + "scrs5" + Path.GetExtension(uploadfile.FileName);
                        Oyun.scr5 = pathForDb;
                        break;
                    case "scrs6":
                        Klasor = Path.Combine(Server.MapPath("~/img/scr"), Oyun.Adi);
                        if (!Directory.Exists(Klasor))
                        {
                            DirectoryInfo di = Directory.CreateDirectory(Klasor);
                        }
                        filePath = Path.Combine(Klasor, ("scrs6" + Path.GetExtension(uploadfile.FileName)));
                        uploadfile.SaveAs(filePath);
                        pathForDb = "/img/scr/" + Oyun.Adi + "/" + "scrs6" + Path.GetExtension(uploadfile.FileName);
                        Oyun.scr6 = pathForDb;
                        break;
                    default:
                        break;
                }
                db.Entry(_oyun).CurrentValues.SetValues(Oyun);
                db.SaveChanges();
               
            }
            return View(Oyun);
        }

        public ActionResult OyunAra()
        {
            return View();
        }

        [HttpGet]
        public ActionResult OyunAra(string aranan)
        {
            SarayContext db = new SarayContext();
            List<Oyun> Oyun = db.Oyunlar.Where(x => x.Adi.Contains(aranan)).ToList();
            return View(Oyun);
        }
        public ActionResult OyunCdKeyEkle(string oyunId)
        {
            int oid = Convert.ToInt32(oyunId);
            ViewData["id"] = oyunId.ToString();
            using (SarayContext db = new SarayContext())
            {
                Oyun Oyun = db.Oyunlar.Where(x => x.Id == oid).Single();

                return View(Oyun);
            }
        }
        [HttpPost]
        public ActionResult OyunCdKeyEkle(string oyunId, string key)
        {
            int oid = Convert.ToInt32(oyunId);
            ViewData["id"] = oyunId.ToString();
            using (SarayContext db = new SarayContext())
            {
                Oyun Oyun = db.Oyunlar.Where(x => x.Id == oid).Single();
                var _oyun = db.Oyunlar.Single(a => a.Id == oid);
                Oyun.CdKey.Add(new CdKey { Durum = false, Key = key, Tarih = DateTime.Now });
                Oyun.StokDurumu += 1;
                db.Entry(_oyun).CurrentValues.SetValues(Oyun);
                db.SaveChanges();
                return View(Oyun);
            }
        }
        public ActionResult IletisimMesajlari()
        {
            SarayContext db = new SarayContext();
            List<Iletisim> msjlr = db.IletisimMesajlari.OrderByDescending(x=>x.Tarih).ToList();

            return View(msjlr);
        }

        public ActionResult OyunBilgileriDuzenle(string oyunId)
        {
            int oid = Convert.ToInt32(oyunId);
            SarayContext db = new SarayContext();
            Oyun Oyun = db.Oyunlar.Where(x => x.Id == oid).Single();
            return View(Oyun);
        }
        [HttpPost]
        public ActionResult OyunBilgileriDuzenle(Oyun oyn)
        {
           using ( SarayContext db = new SarayContext())
           {

           
            Oyun Oyun = db.Oyunlar.Where(x => x.Id == oyn.Id).Single();
            Oyun.Adi = oyn.Adi;
            Oyun.Fiyat = oyn.Fiyat;

WebApplication1/Controllers/OyunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Veri;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class OyunController : Controller
    {
        SarayContext db = new SarayContext();
        //
        // GET: /Oyun/
        public ActionResult Index()
        {
            SarayContext db = new SarayContext();
            List<Oyun> Oyunlar = db.Oyunlar.OrderByDescending(x => x.Tarih).ToList();
            return View(Oyunlar);
        }
        public ActionResult Oyunlar(string kategori)
        {
            ViewData["kategori"] = kategori;
            using (SarayContext db = new SarayContext())
            {

                List<Oyun> Oyunlar = db.Oyunlar.Where(x => x.Kategori.Contains(kategori)).ToList();
                return View(Oyunlar);
            }
        }
        public ActionResult id(int id)
        {
            List<object> myModel = new List<object>();
            myModel.Add(db.Oyunlar.OrderBy(x => x.Tarih).ToList());
            myModel.Add(db.Kullanicilar.ToList());
            myModel.Add(db.Yorumlar.OrderBy(x=>x.Tarih).ToList());
            ViewData["id"] = id.ToString();
            return View(myModel);
        }

        public ActionResult Oyun(int id)
        {
            SarayContext db = new SarayContext();
            Oyun Oyun = db.Oyunlar.Where(x => x.Id == id).SingleOrDefault();
            ViewData["id"] = id.ToString();
            return View(Oyun);
        }
        [HttpPost]
        public ActionResult Oyun(int id, int KullaniciID, string YorumTuru, string Icerik)
        {
            using (SarayContext db = new SarayContext())
            { 
                Yorum _yrm = new Yorum();
                _yrm.OyunID = id;
                _yrm.KullaniciID = KullaniciID;
                _yrm.YorumTuru = YorumTuru;
                _yrm.Icerik = Icerik;
                _yrm.Tarih = DateTime.Now;
                db.Yorumlar.Add(_yrm);
                db.SaveChanges();
            }
            ModelState.Clear();
                SarayContext dba = new SarayContext();
                Oyun Oyun = dba.Oyunlar.Where(x => x.Id == id).SingleOrDefault();
                ViewData["id"] = id.ToString();
                return View(Oyun);

        }
        [HttpPost]
        public ActionResult id(int OyunID, int KullaniciID, string YorumTuru, string Icerik)
        {
            using (SarayContext db = new SarayContext())
            {
                Yorum _yrm = new Yorum();
                _yrm.OyunID = OyunID;
                _yrm.KullaniciID = KullaniciID;
                _yrm.YorumTuru = YorumTuru;
                _yrm.Icerik = Icerik;
                _yrm.Tarih = DateTime.Now;
                db.Yorumlar.Add(_yrm);
                db.SaveChanges();
                List<object> myModel = new List<object>();
                myModel.Add(db.Oyunlar.ToList());
                myModel.Add(db.Kullanicilar.ToList());
                myModel.Add(db.Yorumlar.ToList());
                ViewData["id"] = OyunID.ToString();
                return View(myModel);
            }
        }
        public ActionResult TabYeniCikanlar()
        {
            int i = 0;
            SarayContext db = new SarayContext();
            List<Oyun> _Oyun = new List<Oyun>();
            List<Oyun> Oyun = new List<Oyun>();
            _Oyun=(db.Oyunlar.OrderByDescending(x => x.Tarih).ToList());
            foreach (var item in _Oyun)
            {
                Oyun.Add(item);
                i++;
                if (i>=4)
                {
                    break;
                }
            }
            return View(Oyun);
        }

        public ActionResult TabCokSatanlar()
        {
            int i = 0;
            SarayContext db = new SarayContext();
            List<Oyun> _Oyun = new List<Oyun>();
            List<Oyun> Oyun = new List<Oyun>();
            _Oyun = (db.Oyunlar.OrderByDescending(x => x.Satilan).ToList());
            foreach (var item in _Oyun)
            {
                Oyun.Add(item);
                i++;
                if (i >= 4)
                {
                    break;
                }
            }
            return View(Oyun);
        }


        public ActionResult TabBenzerler(Oyun oyn)
        {
            int adUz, katUz;
            SarayContext db = new SarayContext();
            List<Oyun> Oyun = new List<Oyun>();
            List<Oyun> ad=new List<Oyun>();
            List<Oyun> kategori = new List<Oyun>();
            List<Oyun> genel = new List<Oyun>();
            int i = 0;
            char[] delimiterChars = { ' ', ',', '.', ':', '\t' };
            string[] oyunAdiKelime = oyn.Adi.Split(delimiterChars);
            string[] kategoriKelime = oyn.Kategori.Split(delimiterChars);
            foreach (string s in oyunAdiKelime)
            {
                ad= db.Oyunlar.Where(x => x.Adi.Contains(s)).ToList();
                ad.Remove(db.Oyunlar.Where(x => x.Id == oyn.Id).Single());
            }
            adUz = ad.Count();
            foreach (string s in kategoriKelime)
            {
                kategori = db.Oyunlar.Where(x => x.Adi.Contains(s)).ToList();
                kategori.Remove(db.Oyunlar.Where(x => x.Id == oyn.Id).Single());
            }
            katUz = kategori.Count();
            genel = db.Oyunlar.ToList();
            genel.Remove(db.Oyunlar.Where(x => x.Id == oyn.Id).Single());
            foreach (var item in ad)
            {
                Oyun.Add(item);
                i++;
                if (i >= 4)
                {
                    break;
                }
            }
            i = 0;
            if (adUz<4)
            {
                foreach (var item in kategori)
                {
                    Oyun.Add(item);
                    i++;
                    if (i >= (4-adUz))
                    {
                        break;
                    }
                }
                i = 0;
                if (adUz+katUz<4)
                {
                    foreach (var item in genel)
                    {
                        Oyun.Add(item);
                        i++;
                        if (i >= (4 - adUz+katUz))
                        {
                            break;
                        }
                    }
                }
            }
            return View(Oyun);
        }

    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SARAYGAME</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/styles.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/font-awesome.min.css")

</head>
<body style="padding-top:0px; padding-bottom:0px; margin-bottom:0px; margin-top:0px;">
    <div class="row" style="background-color: rgba(0, 0, 0,1); border-bottom: 1px solid #232323; ">
        <div class="container" style="min-width: 75%;">

            <div class="col-xs-12" style="padding-top: 0px; margin-top: 10px; padding-bottom: 0px;">
                <div class="row" style="padding-bottom:10px;">
                    <div class=" col-sm-6" style="padding-bottom:10px;">
                        @using (Html.BeginForm("Ara", "Home", FormMethod.Get))
                        {
                            <div class="input-group" style=" ">
                                <input name="aranan" type="text" class="form-control" style="width: 100%; color: white; background-color: rgba(0, 0, 0, 0.90); max-width: 2000px; " placeholder="@WebApplication1.Resources.HomeTexts.Ara...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" style="color: white; background-color: rgba(0, 0, 0, 0.90); " type="submit">@WebApplication1.Resources.HomeTexts.Git</button>
                                </span>
                            </div>
                        }
                    </div>
                    <div class=" col-sm-6" style="">
                        <div class="col-xs-9 col-md-10" align="left" style="padding:0px;">
                            @if (Session["KullaniciID"] != null)
                            {
                                <div class="row">
                                    <a style="float:left; padding-right:1%;" href="@Url.Action("Index","Kullanici")"> <img class=" img-rounded" id="profilResmi" style="height:40px; width:40px;" src="/img/profil/@(Session["ProfilResmi"]) " /></a>
                                    <span style="float:left; padding:1%;">@Session["KullaniciAdi"] @WebApplication1.Resources.HomeTexts.Bakiyeniz : @Session["Bakiye"] ₺</span>
                                    <a style="float:right; padding:1%;" href="@Url.Action("Cikis","Hesap")"> Çıkış</a>
                                    @if (Session["KullaniciAdmin"] == "1")
                                    {
                                        <a style="float:right; padding:1%;" href="@Url.Action("Index","Admin")"> @WebApplication1.Resources.HomeTexts.AdminPaneli</a>
                                    }
                                </div>
                            }
                            else
                            {
                                <a href="@Url.Action("UyeOl","Hesap")" class="btn btn-default btn-md" style="width: 49%; color: white; background-color: rgba(0, 0, 0, 0.90);">
                                    @WebApplication1.Resources.HomeTexts.UyeOl
                                </a>
                                <a href="@Url.Action("Giris","Hesap")" class="btn btn-default btn-md" style="width: 49%; color: white; background-color: rgba(0, 0, 0, 0.90); ">
                                    @WebApplication1.Resources.HomeTexts.GirisYap
                                </a>
                            }
                        </div>
                        <div class="col-xs-3 col-md-2" align="right" style="padding:0px;">
                            <a href="@Url.Action("Degistir", "Dil", new { LanguageAbbrevation="tr"},null)"><img src="/img/lang/tr.png" style="width:30%;" /></a>
                            <a href="@Url.Action("Degistir", "Dil", new { LanguageAbbrevation="en"},null)"><img src="/img/lang/en.png" style="width:30%;" /></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <nav class="navbar navbar-inverse" style="background-color:#131212; color:white; border-width:0px;">
            <div class="container" style="min-width:75%;">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" id="" style="color:white;" href="@Url.Action("Index","Home")"><img src="~/img/icon/site.png" style="height:25px; width:50px; padding:0px;" /></a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>   -->
                        <li class="dropdown">
                            <a id="" style=" color:white;" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@WebApplication1.Resources.HomeTexts.Oyunlar <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Aksiyon"})">@WebApplication1.Resources.HomeTexts.Aksiyon</a></li>
                                <li><a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Macera"})">@WebApplication1.Resources.HomeTexts.Macera</a></li>
                                <li><a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Strateji"})">@WebApplication1.Resources.HomeTexts.Strateji</a></li>
                                <li><a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Spor"})">@WebApplication1.Resources.HomeTexts.Spor</a></li>
                                <li><a href="@Url.Action("Oyunlar", "Oyun", new { kategori="Yaris"})">@WebApplication1.Resources.HomeTexts.Yaris</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Index", "Oyun")">TÜMÜ</a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a id="" style="color:white;" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@WebApplication1.Resources.HomeTexts.OnlineOyunlar <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">MMORPG</a></li>
                                <li><a href="#">FPS</a></li>
                                <li><a href="#">TPS</a></li>
                                <li role="separator" class="divider"></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a id="" style="color:white;" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@WebApplication1.Resources.HomeTexts.Donanim <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">KLAVYE</a></li>
                                <li><a href="#">MOUSE</a></li>
                                <li><a href="#">KULAKLIK</a></li>
                                <li><a href="#">KONSOL</a></li>
                                <li role="separator" class="divider"></li>
                            </ul>
                        </li>
                        <li><a id="" style="color:white;" href="#">@WebApplication1.Resources.HomeTexts.OyunEsyalari</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a id="" style="color:white;" href="#">@WebApplication1.Resources.HomeTexts.Hakkimizda</a></li>
                        <li><a id="" style="color:white;" href="@Url.Action("Iletisim", "Home")">@WebApplication1.Resources.HomeTexts.Iletisim</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
    <div class="container body-content" style="min-width:75%; min-height:624px;">
        @RenderBody()
    </div>
    <footer style="padding-bottom:0px; bottom:0; width:100%;">

        <div class="container" style="padding-bottom:0px;">
        </div>
        <div class="row" style="background-color: rgb(0, 0, 0); " align="center">
            <div class="row">
                <h4>SARAYGAME</h4>
                <p id="yorum"> Copyright 2016 SarayGame San. ve Tic. A.Ş.</p>
            </div>
            <div class="row">
                <a id="" style="color:white;" href="@Url.Action("Iletisim", "Home")">@WebApplication1.Resources.HomeTexts.Iletisim</a>
                |
                <a id="" style="color:white;" href="#">@WebApplication1.Resources.HomeTexts.Hakkimizda</a>
            </div>
            <div class=" row">
                <a href="#" style="color:white;"><i class="fa fa-facebook-official fa-3x" aria-hidden="true"></i></a>
                <a href="#" style="color:white;"><i class="fa fa-twitter-square fa-3x" aria-hidden="true"></i> </a>
                <a href="#" style="color:white;"><i class="fa fa-google-plus-square fa-3x" aria-hidden="true"></i></a>
                <a href="#" style="color:white;"><i class="fa fa-instagram fa-3x" aria-hidden="true"></i></a>
            </div>
            <a href="#">
                <img alt="" src="http://www.credit-card-logos.com/images/visa_credit-card-logos/visa_mastercard_1.gif" width="166" height="50" border="0" />
            </a>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_LayoutUrunler.cshtml
@{
    ViewBag.Title = "_LayoutUrunler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="jumbotron" style="background-color: rgba(0, 0, 0, 0.94); " align="center">
    <div class=" row">
        <h2 style="color:white;">@Html.ActionLink("Yaptığım Layout Sayfasına Gitmek İçin Tıklayınız", "Oyun", "Home")</h2>
    </div>
</div>
<div class="jumbotron" style="background-color: rgba(0, 0, 0, 0.94); " align="center">
    <div class=" row">
        <div class="col-md-6" style="padding-bottom:20px;">
            <div class="row" style="width: 100%; padding-top: 56.25%; border: 1px solid #232323; ">

            </div>
        </div>
        <div class="col-md-6">
            <div class="row">

                <div class="col-xs-6" style="padding-bottom:20px;">
                    <div class="row" style=" width: 100%; padding-top:120%; border: 1px solid #232323; ">

                    </div>
                </div>

                <div class="col-xs-6" style="padding-bottom:20px;">
                    <div class="row" style="width: 100%; padding-top: 120%; border: 1px solid #232323; ">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="jumbotron" style="background-color: rgba(0, 0, 0, 0.94); " align="center">
    <div class=" row">
        <div class="col-md-6" style="padding-bottom:20px;">
            <div class="row">

                <div class="col-xs-6">
                    <div class="row" style=" width: 100%; padding-top:120%; border: 1px solid #232323; ">

                    </div>
                </div>

                <div class="col-xs-6">
                    <div class="row" style="width: 100%; padding-top: 120%; border: 1px solid #232323; ">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6" style="padding-bottom:20px;">
            <div class="row">

                <div class="col-xs-6">
                    <div class="row" style=" width: 100%; padding-top:120%; border: 1px solid #232323; ">

                    </div>
                </div>

                <div class="col-xs-6">
                    <div class="row" style="width: 100%; padding-top: 120%; border: 1px solid #232323; ">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class=" row">
        <div class="col-md-6" style="padding-bottom:20px;">
            <div class="row">

                <div class="col-xs-6">
                    <div class="row" style=" width: 100%; padding-top:120%; border: 1px solid #232323; ">

                    </div>
                </div>

                <div class="col-xs-6">
                    <div class="row" style="width: 100%; padding-top: 120%; border: 1px solid #232323; ">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6" style="padding-bottom:20px;">
            <div class="row">

                <div class="col-xs-6">
                    <div class="row" style=" width: 100%; padding-top:120%; border: 1px solid #232323; ">

                    </div>  
                </div>

                <div class="col-xs-6">
                    <div class="row" style="width: 100%; padding-top: 120%; border: 1px solid #232323; ">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@RenderBody()