WebApplication1/Models/Kullanici.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class Kullanici
    {
        public int ID { get; set; }
        [Required(ErrorMessage="Ad Alanı Boş Bırakılamaz")]
        public string Adi { get; set; }
        [Required(ErrorMessage = "Soyad Alanı Boş Bırakılamaz")]
        public string Soyadi { get; set; }
        [Required(ErrorMessage = "Kullanıcı Adı Alanı Boş Bırakılamaz")]
        public string KullaniciAdi { get; set; }
        [Required(ErrorMessage = "Parola Alanı Boş Bırakılamaz")]
        [DataType(DataType.Password)]
        public string Parola { get; set; }
        public DateTime KayitTarihi { get; set; }
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Geçerli Bir E-Mail Adresi Girin")]
        public string Email { get; set; }
        [Compare("Parola", ErrorMessage = "Lütfen Şifrenizi Doğru Giriniz.")]
        [DataType(DataType.Password)]
        public string OnaylaParola { get; set; }
        public bool Admin { get; set; }
        public string ProfilResmi { get; set; }
        public double Bakiye { get; set; }

        public virtual ICollection<Yorum> Yorumlar { get; set; }
        public virtual ICollection<OyunSiparis> OyunSiparis { get; set; }

    }
}

WebApplication1/Controllers/HesapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Veri;
namespace WebApplication1.Controllers
{
    public class HesapController : Controller
    {
        //
        // GET: /Hesap/
        public ActionResult Index()
        {
            using (SarayContext db=new SarayContext())
            {
                return View(db.Kullanicilar.ToList());
            }
        }
        public ActionResult UyeOl()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UyeOl(Kullanici Hesap)
        {
            if (ModelState.IsValid)
            {
                using(SarayContext db=new SarayContext())
                {
                    Hesap.KayitTarihi = DateTime.Now;
                    Hesap.Admin = false;
                    Hesap.ProfilResmi = "varsayilan.png";
                    Hesap.Bakiye = 0;
                    db.Kullanicilar.Add(Hesap);
                    db.SaveChanges();
                }
            ModelState.Clear();
            ViewBag.Message = Hesap.Adi + " " + Hesap.Soyadi + "Başarıyla Kayıt Oldu";
            }
            return View();
        }
        //Login
        public ActionResult Giris()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Giris(Kullanici kullanici)
        {
            using(SarayContext db=new SarayContext())
            {
                var usr = db.Kullanicilar.Where(i => i.KullaniciAdi == kullanici.KullaniciAdi && i.Parola == kullanici.Parola).FirstOrDefault();
                if(usr!=null)
                {
                    Session["KullaniciID"] = usr.ID.ToString();
                    Session["KullaniciAdi"] = usr.KullaniciAdi.ToString();
                    Session["ProfilResmi"] = usr.ProfilResmi.ToString();
                    Session["Bakiye"] = usr.Bakiye.ToString();
                    if (usr.Admin == true)
                        Session["KullaniciAdmin"] = "1";
                    else
                        Session["KullaniciAdmin"] = "0";
                    return RedirectToAction("Index","Home");
                }
                else
                {
                    ModelState.AddModelError("", "Kullanıcı Adı veya Parola Yanlış.");
                }
            }
            return View();
        }
        public ActionResult LoggedIn()
        {
            if (Session["KullaniciID"]!=null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Giris");
            }
        }
        public ActionResult Cikis()
        {
            Session.Abandon();
            return RedirectToAction("Giris");
        }
	}
}

WebApplication1/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Veri;

namespace WebApplication1.Controllers
{
    public class KullaniciController : Controller
    {
        //
        // GET: /Kullanici/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Siparislerim()
        {
            return View();
        }
        public ActionResult OyunSiparislerim()
        {
           int kid = Convert.ToInt32(Session["KullaniciID"]);
            SarayContext db = new SarayContext();
            List<OyunSiparis> siparislerim = db.OyunSiparis.Where(x => x.KullaniciID == kid).ToList();
            return View(siparislerim);
        }
        public ActionResult OnlineOyunSiparislerim()
        {
            return View();
        }
        public ActionResult BakiyeYukle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult BakiyeYukle(double bky)
        {
            int kid=Convert.ToInt32(Session["KullaniciID"]);
            SarayContext db = new SarayContext();
            Kullanici Kullanici = db.Kullanicilar.Where(x => x.ID == kid).Single();
            Kullanici.Bakiye += bky;
            var _kullanici = db.Kullanicilar.Single(a => a.ID == kid);
            db.Entry(_kullanici).CurrentValues.SetValues(Kullanici);
            db.SaveChanges();
            Session["Bakiye"] = _kullanici.Bakiye;
            return View();
        }
        public ActionResult Duzenle()
        {
            int kid = Convert.ToInt32(Session["KullaniciID"]);
            SarayContext db=new SarayContext();
            Kullanici Kullanici = db.Kullanicilar.Where(x => x.ID == kid).Single();
            return View(Kullanici);
        }
        [HttpPost]
        public ActionResult Duzenle(Kullanici klnc)
        {
            if (klnc.Parola == klnc.OnaylaParola)
            {
                int kid = Convert.ToInt32(Session["KullaniciID"]);
                using (SarayContext db = new SarayContext())
                {
                    Kullanici Kullanici = db.Kullanicilar.Where(x => x.ID == kid).Single();
                    var _kullanici = db.Kullanicilar.Single(a => a.ID == kid);
                    Kullanici.Adi = klnc.Adi;
                    Kullanici.Email = klnc.Email;
                    Kullanici.OnaylaParola = klnc.OnaylaParola;
                    Kullanici.Parola = klnc.Parola;
                    Kullanici.Soyadi = klnc.Soyadi;
                    db.Entry(_kullanici).CurrentValues.SetValues(Kullanici);
                    db.SaveChanges();
                    return View(Kullanici);
                }
            }
            else
            {
                int kid = Convert.ToInt32(Session["KullaniciID"]);
                SarayContext db = new SarayContext();
                Kullanici Kullanici = db.Kullanicilar.Where(x => x.ID == kid).Single();
                return View(Kullanici);
            }
        }
        public ActionResult ProfilResmiGuncelle(HttpPostedFileBase uploadfile)
        {
            int kid = Convert.ToInt32(Session["KullaniciID"]);
            SarayContext db = new SarayContext();
            Kullanici Kullanici = db.Kullanicilar.Where(x => x.ID == kid).Single();
            var _kullanici = db.Kullanicilar.Single(a => a.ID == kid);
            string Klasor, filePath, pathForDb;
            if (uploadfile.ContentLength > 0)
            {
                Klasor = Path.Combine(Server.MapPath("~/img/profil"));
                if (!Directory.Exists(Klasor))
                {
                    DirectoryInfo di = Directory.CreateDirectory(Klasor);
                }
                filePath = Path.Combine(Klasor, (Kullanici.Adi + Path.GetExtension(uploadfile.FileName)));
                uploadfile.SaveAs(filePath);
                pathForDb = Kullanici.Adi + Path.GetExtension(uploadfile.FileName);
                Kullanici.ProfilResmi = pathForDb;
                db.Entry(_kullanici).CurrentValues.SetValues(Kullanici);
                db.SaveChanges();
            }
            return RedirectToAction("Duzenle", "Kullanici");
        }
    }
}

WebApplication1/Views/Kullanici/BakiyeYukle.cshtml
@model WebApplication1.Models.Kullanici

@{
    ViewBag.Title = "BakiyeYukle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if(Session["KullaniciID"]!=null)
{
<div class="container" style="background-color: rgba(0, 0, 0, 0.94);  " align="center">
    <div class="row" id="GradTransparanSiyahTransparan" style="font-size:20px;" align="center">
       Bakiye Yükle
    </div>
</div>
<br />
<div class="container" style="background-color: rgba(0, 0, 0, 0.94);  " align="center">
    <div class="row" id="GradTransparanSiyahTransparan" style="height:20px;" align="center">
    </div>
    <div class="row" style="margin:3%;" align="left">
        <div class="col-md-2" align="center" style="@if(Session["KullaniciAdmin"]=="1"){<text>color:red;</text>}">
            @Session["KullaniciAdi"]
            <img class=" img-rounded" id="profilResmi" style="height:100%;" src="/img/profil/@(Session["ProfilResmi"]) " />
        </div>
        <div class="col-md-9">
            @using (Html.BeginForm("BakiyeYukle", "Kullanici", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <label style="font-size:14px; color:rgba(123, 123, 123, 0.81)" for="comment">Ne Kadar Yüklemek İstiyorsunuz.</label>
                    <input type="text" name="bky" id="bky" />
                    <button type="submit" class="btn btn-default" style="color:white; background-color:rgba(117, 117, 117, 0.93)" name="yorum_buton">Yükle</button>
                </div>
               
            }
        </div>
    </div>

    <div class="row" id="GradTransparanSiyahTransparan" style="height:20px;" align="center">

    </div>
</div>
}
else
{
<text><h1 style="color:black;"><a href="@Url.Action("Giris","Hesap")">GİRİŞ YAPMALISINIZ.</a></h1></text>
}

WebApplication1/Views/Kullanici/Duzenle.cshtml
@model WebApplication1.Models.Kullanici

@{
    ViewBag.Title = "Duzenle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Session["KullaniciID"] != null)
{
<div class="container" style="background-color: rgba(0, 0, 0, 0.94);  " align="center">
    <div class="row" id="GradTransparanSiyahTransparan" style="font-size:20px;" align="center">
        Profilimi Düzenle
    </div>
</div>
<div class="container" style="background-color: rgba(0, 0, 0, 0.94);  " align="left">
    <div class="row" style="padding:1%;">
        <div class="col-md-2" align="center">
            Profil Resmi :
            <br />
            <img src="/img/profil/@(Model.ProfilResmi)" style="width:100%;" />
        </div>
        <div class="col-md-3">
            <br />
            <form action="@Url.Action("ProfilResmiGuncelle", "Kullanici")" method="post" enctype="multipart/form-data">
                <input type="file" name="uploadfile" id="uploadfile" style="color: white; width:100%; background-color: rgba(0, 0, 0, 0.90); border:1px solid #232323; " />
                <br />
                <input type="submit" value="Profil Resmi Güncelle" class="btn btn-default" style="float: left;color: white; background-color: rgba(0, 0, 0, 0.90);  min-width: 100%;" />

            </form>
        </div>

    </div>
</div>
<div class="container" style="background-color: rgba(0, 0, 0, 0.94);  " align="center">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.Adi, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Adi)
                    @Html.ValidationMessageFor(model => model.Adi)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Soyadi, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Soyadi)
                    @Html.ValidationMessageFor(model => model.Soyadi)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Parola, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Parola)
                    @Html.ValidationMessageFor(model => model.Parola)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OnaylaParola, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OnaylaParola)
                    @Html.ValidationMessageFor(model => model.OnaylaParola)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email)
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>



}
else
{
<text><h1 style="color:black;"><a href="@Url.Action("Giris","Hesap")">GİRİŞ YAPMALISINIZ.</a></h1></text>
}

WebApplication1/Views/Kullanici/Index.cshtml
@{
    ViewBag.Title = "Hesabım";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Session["KullaniciID"] != null)
{
<div class="container" style="background-color: rgba(0, 0, 0, 0.94);  " align="center">
    <div class="row" id="GradTransparanSiyahTransparan" style="font-size:20px;" align="center">
        HESABIM
    </div>
</div>
<br />
<div class="container" style="background-color: rgba(0, 0, 0, 0.94);  " align="center">
    <div class="row" id="GradTransparanSiyahTransparan" style="height:20px;" align="center">
    </div>
    <div class="row" style="margin:3%;" align="left">
        <div class="col-md-2" align="center" style="@if(Session["KullaniciAdmin"]=="1"){<text>color:red;</text>}">
            @Session["KullaniciAdi"]
        <img class=" img-rounded" id="profilResmi" style="height:100%;" src="/img/profil/@(Session["ProfilResmi"]) " />
        </div>
        <div class="col-md-9">
            <div class="row" style="" align="center">
                <div class="col-md-4" id="circle" style="margin:3%;">
                    <a style="color:white;" href="@Url.Action("Duzenle","Kullanici")"><br /><br /><br />Hesabımı Düzenle</a>
                </div>
                <div class="col-md-4" id="circle" style="margin:3%;">
                    <a style="color:white;" href="@Url.Action("OyunSiparislerim","Kullanici")"><br /><br /><br />Oyun Siparişlerim</a>
                </div>
                <div class="col-md-4" id="circle" style="margin:3%;">
                    <a style="color:white;" href="@Url.Action("BakiyeYukle","Kullanici")"><br /><br /><br />Bakiye Yükle</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="GradTransparanSiyahTransparan" style="height:20px;" align="center">

    </div>
</div>



}
else
{
<text><h1 style="color:black;"><a href="@Url.Action("Giris","Hesap")">GİRİŞ YAPMALISINIZ.</a></h1></text>
}

WebApplication1/Views/Kullanici/OyunSiparislerim.cshtml
@model IEnumerable<WebApplication1.Models.OyunSiparis>

@{
    ViewBag.Title = "OyunSiparislerim";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container" style="background-color: rgba(0, 0, 0, 0.94); min-width:100%; padding:3%;" align="center">
    @if (Session["KullaniciID"] != null)
    {
        <text>
    <div class="row">
        <div class=" col-md-3" align="center">
            Oyun Adı
        </div>
        <div class=" col-md-1" align="center">
            Fiyat
        </div>
        <div class=" col-md-3" align="center">
            Tarih
        </div>
        <div class=" col-md-5" align="center">
            CD-KEY
        </div>
    </div>
    <br />
        </text>
        foreach (var item in Model)
        {
            <text>
    <div class="row">
        <div class=" col-md-3" align="center">
            @(item.Oyun.Adi)
        </div>
        <div class=" col-md-1" align="center">
            @(item.Oyun.Fiyat)
        </div>
        <div class=" col-md-3" align="center">
            @(item.Tarih)
        </div>
        <div class=" col-md-5" align="center">
            @(item.CdKey.Key)
        </div>
    </div>
                <br />
            </text>
        }

    }
    else
    {
        <text>Lütfen Giriş Yapın</text>
    }
</div>
<br />
<br />

WebApplication1/Views/Kullanici/Siparislerim.cshtml
@{
    ViewBag.Title = "Siparislerim";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Session["KullaniciID"] != null)
{
<div class="container" style="background-color: rgba(0, 0, 0, 0.94);  " align="center">
    <a href="@Url.Action("OyunSiparislerim", "Kullanici")">Oyun Siparislerim</a>
    <a href="@Url.Action("OnlineOyunSiparislerim", "Kullanici")">Online Oyun Siparislerim</a>

</div>

}
else
{
<text><h1 style="color:black;"><a href="@Url.Action("Giris","Hesap")">GİRİŞ YAPMALISINIZ.</a></h1></text>
}